{
 "title": "CMCD Dashboard v2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CMCD Messages Received",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "cmcd_metrics",
     "query": "SELECT \"cmcd_key_sid\" FROM \"cmcd_metrics\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "cmcd_data" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CMCD Messages by Mode",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "cmcd_mode::tag" ], "type": "tag" }
     ],
     "measurement": "cmcd_metrics",
     "query": "SELECT \"cmcd_key_sid\" FROM \"cmcd_metrics\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "cmcd_data" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Buffer Lenght by SID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "cmcd_key_sid::tag" ], "type": "tag" }
     ],
     "measurement": "cmcd_metrics",
     "select": [
      [
       { "params": [ "cmcd_key_bl" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mean Buffer Lenght",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cmcd_metrics",
     "select": [
      [
       { "params": [ "cmcd_key_bl" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# Unique Sessions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "cmcd_key_sid::tag" ], "type": "tag" }
     ],
     "measurement": "cmcd_metrics",
     "query": "SELECT \"cmcd_key_sid\" FROM \"cmcd_metrics\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "cmcd_data" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Most Watched Content",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "cmcd_key_cid::tag" ], "type": "tag" },
      { "params": [ "cmcd_key_sid::tag" ], "type": "tag" }
     ],
     "measurement": "cmcd_metrics",
     "select": [
      [
       { "params": [ "cmcd_data" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Buffer Starvation by SID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "cmcd_key_sid::tag" ], "type": "tag" }
     ],
     "measurement": "cmcd_metrics",
     "select": [
      [
       { "params": [ "cmcd_key_bs" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Measured Throughput by SID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "cmcd_key_sid::tag" ], "type": "tag" }
     ],
     "measurement": "cmcd_metrics",
     "select": [
      [
       { "params": [ "cmcd_key_mtp" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mean Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cmcd_metrics",
     "select": [
      [
       { "params": [ "cmcd_key_ltc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency per Content",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cmcd_key_cid::tag" ], "type": "tag" }
     ],
     "measurement": "cmcd_metrics",
     "select": [
      [
       { "params": [ "cmcd_key_ltc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Encoded Bitrate by SID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "cmcd_key_sid::tag" ], "type": "tag" }
     ],
     "measurement": "cmcd_metrics",
     "select": [
      [
       { "params": [ "cmcd_key_br" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Bitrate by SID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "cmcd_key_sid::tag" ], "type": "tag" }
     ],
     "measurement": "cmcd_metrics",
     "select": [
      [
       { "params": [ "cmcd_key_tb" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Session IDs",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "cmcd_key_sid::tag" ], "type": "tag" },
      { "params": [ "request_user_agent::tag" ], "type": "tag" }
     ],
     "measurement": "cmcd_metrics",
     "query": "SELECT count(\"cmcd_data\"), last(\"cmcd_key_sta\") AS \"status\", last(\"cmcd_key_v\") AS \"cmcd_version\", last(\"cmcd_key_st\") AS \"stream_type\", last(\"cmcd_key_pr\") AS \"playback_rate\" FROM \"cmcd_metrics\" WHERE $timeFilter GROUP BY \"cmcd_key_sid\"::tag, \"request_user_agent\"::tag",
     "select": [
      [
       { "params": [ "cmcd_data" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ],
      [
       { "params": [ "cmcd_key_sta" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "status" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency by SID",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "cmcd_key_sid::tag" ], "type": "tag" }
     ],
     "measurement": "cmcd_metrics",
     "select": [
      [
       { "params": [ "cmcd_key_ltc" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Buffer Drain by SID (Option 2)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "query": "SELECT \"cmcd_key_br\", \"cmcd_key_mtp\" FROM \"cmcd_metrics\" WHERE $timeFilter GROUP BY \"cmcd_key_sid\"::tag"
    }
   ]
  }
 ]
}